# Generated by Django 3.1.2 on 2020-10-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kecheng',
            fields=[
                ('c_bh', models.AutoField(help_text='主键', primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('c_xueke', models.CharField(help_text='学科', max_length=32, verbose_name='学科')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('c_bh', models.CharField(help_text='c_bh', max_length=32, primary_key=True, serialize=False, verbose_name='学生编号')),
                ('c_name', models.CharField(help_text='学生姓名', max_length=16, verbose_name='学生姓名')),
                ('c_age', models.IntegerField(help_text='年龄', max_length=3, verbose_name='年龄')),
                ('c_sex', models.CharField(help_text='性别', max_length=2, verbose_name='性别')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('c_bh', models.CharField(help_text='c_bh', max_length=32, primary_key=True, serialize=False, verbose_name='教师编号')),
                ('c_name', models.CharField(help_text='老师姓名', max_length=32, verbose_name='老师姓名')),
                ('n_age', models.IntegerField(help_text='年龄', max_length=3, verbose_name='年龄')),
                ('c_sex', models.CharField(help_text='性别', max_length=2, verbose_name='性别')),
                ('c_x_bh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.kecheng')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('c_bh', models.AutoField(help_text='主键', primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('c_fenshu', models.IntegerField(help_text='分数', max_length=4, verbose_name='分数')),
                ('c_s_bh', models.ForeignKey(help_text='学生编号', null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.student', verbose_name='学生编号')),
                ('c_x_bh', models.ForeignKey(help_text='课程编号', on_delete=django.db.models.deletion.CASCADE, to='firstapp.kecheng', verbose_name='课程编号')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
